name: Pipeline CI

on:
    push:
        branches: [develop, main]
    pull_request:
        branches: [develop, main]

jobs:
    test:
        name: Run unit test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            
            - name: Install dependencies
              run: pip install pytest

            - name: Run unit tests
              run: pytest tests/unit/ -v
        